version: '3.8'

services:
  availability-service:
    build: .
    ports:
      - "5010:5010"
    environment:
      - MONGO_URI=mongodb://mongo:27017/availability-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
