version: '3.8'

services:
  vehicle-history-service:
    build: .
    ports:
      - "5014:5014"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vehicle-history-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
