version: '3.8'

services:
  user-management-service:
    build: .
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
