version: '3.8'

services:
  active-sessions-service:
    build: .
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sessions-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
