version: '3.8'

services:
  login-audit-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/audit-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
