version: '3.8'

services:
  reservation-service:
    build: .
    ports:
      - "5024:5024"
    environment:
      - MONGO_URI=mongodb://mongo:27017/reservation-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
