version: '3.8'

services:
  exit-service:
    build: .
    ports:
      - "5016:5016"
    environment:
      - MONGO_URI=mongodb://mongo:27017/exit-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
