version: '3.8'

services:
  ticket-service:
    build: .
    ports:
      - "5022:5022"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ticket-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
