version: '3.8'

services:
  cancellation-service:
    build: .
    ports:
      - "5026:5026"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cancellation-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
