version: '3.8'

services:
  parking-slots-service:
    build: .
    ports:
      - "5009:5009"
    environment:
      - MONGO_URI=mongodb://mongo:27017/slots-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
