version: '3.8'

services:
  rate-management-service:
    build: .
    ports:
      - "5020:5020"
    environment:
      - MONGO_URI=mongodb://mongo:27017/rates-db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
