name: Deploy Student Microservices to EC2
 
on:
  push:
    branches:
      - ramaQA  
 
jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Create Student Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./backEnd
          file: ./backend/Authentication_and_Users/auth-service/Dockerfile
          push: true
          tags: leochicaza/auth-service:latest
 
      
 
 
  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images
 
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}
 
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
              echo "Docker instalado correctamente."
            else
              echo "Docker ya está instalado."
            fi
 
            
            
    
 
            
            sudo docker stop auth-service || true
            sudo docker rm auth-service || true
 
            
            sudo docker pull leochicaiza/auth-service:latest
            
 
            
            sudo docker run -d --name auth-service --env-file .env -p 8001:8001 leochicaiza/auth-service:latest
            
